import Head from "next/head";

import { MainLayout } from "@/layouts/main-layout.component";
import DocumentParserComponent from "@/components/document-parcer/document-parser.component";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <DocumentParserComponent />
      </MainLayout>
    </>
  );
}
